spring.application.name=livraria-doacoes

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres

spring.datasource.username=postgres.ptbgsdqkpfojqckeiqsc
spring.datasource.password=10j20m30K@@@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true